server-list:
  spoof: true
  spoofed-player-count: 1

spoof-tab-list: true

players:
  hide-join: true
  hide-leave: true
  hide-death: true
  hide-revive: true
  hide-name-tags: true

allow-revive: true

proximity-radius: 48
chat:
  allow-whispers: false
  allow-global-chat: false
